---
- name: Create CNI plugins directory
  ansible.builtin.file:
    path: /opt/cni/bin
    state: directory
    mode: "755"

- name: Extract CNI plugins archive
  ansible.builtin.unarchive:
    src: "{{ k8s_common_download_dir }}/{{ k8s_common_cni_plugins_archive }}"
    dest: /opt/cni/bin/
    mode: "755"
