---
- name: Create a symlink from runc to crun
  ansible.builtin.file:
    src: /usr/bin/crun
    dest: /usr/local/sbin/runc
    state: link
    mode: "755"

- name: Download containerd binary archive
  ansible.builtin.get_url:
    url: "{{ k8s_common_containerd_url }}"
    timeout: 30
    dest: "{{ temp_dir.path }}/{{ k8s_common_containerd_archive }}"
    mode: "755"

- name: Extract containerd binary archive
  ansible.builtin.unarchive:
    src: "{{ temp_dir.path }}/{{ k8s_common_containerd_archive }}"
    dest: /usr/local/
    remote_src: true
    list_files: true
    mode: "755"

- name: Download & install containerd service
  ansible.builtin.get_url:
    url: "{{ k8s_common_containerd_service_url }}"
    dest: /usr/lib/systemd/system/containerd.service
    mode: "644"

- name: Load service
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: containerd
    enabled: true
    state: started
