---
- name: Create configuration directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "755"

- name: Create configuration file
  ansible.builtin.template:
    src: containerd_config.toml.j2
    dest: /etc/containerd/config.toml
    mode: "644"
  notify: Restart containerd
