---
- name: Install runc
  ansible.builtin.copy:
    src: "{{ k8s_common_download_dir }}/runc"
    dest: /usr/local/sbin/runc
    mode: "755"

- name: Create a runc symlink for root access
  ansible.builtin.file:
    src: /usr/local/sbin/runc
    dest: /usr/bin/runc
    state: link
    mode: "755"

- name: Extract containerd binary archive
  ansible.builtin.unarchive:
    src: "{{ k8s_common_download_dir }}/{{ k8s_common_containerd_archive }}"
    dest: /usr/local/
    mode: "755"

- name: Create a containerd symlink for root access
  ansible.builtin.file:
    src: /usr/local/bin/containerd
    dest: /usr/bin/containerd
    state: link
    mode: "755"

- name: Install containerd service
  ansible.builtin.copy:
    src: "{{ k8s_common_download_dir }}/containerd.service"
    dest: /usr/lib/systemd/system/containerd.service
    mode: "644"

- name: Load service
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: containerd
    enabled: true
    state: started
