---
- name: Extract crictl binary archive
  ansible.builtin.unarchive:
    src: "{{ k8s_common_download_dir }}/{{ k8s_common_crictl_archive }}"
    dest: /usr/local/bin/
    mode: "755"

- name: Create a crictl symlink for root access
  ansible.builtin.file:
    src: /usr/local/bin/crictl
    dest: /usr/bin/crictl
    state: link
    mode: "755"

# Reference: https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md
- name: Configure crictl
  ansible.builtin.template:
    src: crictl_config.yaml.j2
    dest: /etc/crictl.yaml
    mode: "644"
