---
- name: Create temporary directory for downloads
  ansible.builtin.tempfile:
    state: directory
  register: temp_dir

- name: Configure system and kernel settings
  ansible.builtin.import_tasks: system.yaml

- name: Enable services used by Longhorn
  when: k8s_common_storage == 'longhorn'
  ansible.builtin.import_tasks: longhorn.yaml
  tags:
    - storage
    - longhorn

- name: Enable services used by OpenEBS
  when: k8s_common_storage == 'openebs'
  ansible.builtin.import_tasks: openebs.yaml
  tags:
    - storage
    - openebs

- name: Install containerd
  ansible.builtin.import_tasks: containerd_install.yaml
  tags:
    - container_runtime

- name: Install CNI plugins
  ansible.builtin.import_tasks: cni_plugins.yaml
  tags:
    - cni_plugins

- name: Configure containerd
  ansible.builtin.import_tasks: containerd_config.yaml
  tags:
    - container_runtime

- name: Install & configure crictl
  ansible.builtin.import_tasks: crictl.yaml
  tags:
    - container_tools

- name: Install kubelet
  ansible.builtin.import_tasks: kubelet.yaml

- name: Install kubeadm & kubectl
  ansible.builtin.get_url:
    url: "{{ k8s_common_base_url }}/{{ item }}"
    timeout: 30
    dest: "/usr/local/bin/{{ item }}"
    mode: "755"
  loop:
    - kubeadm
    - kubectl

- name: Create kubeadm & kubectl symlinks for root access
  ansible.builtin.file:
    src: /usr/local/bin/{{ item }}
    dest: /usr/bin/{{ item }}
    state: link
    mode: "755"
  loop:
    - kubeadm
    - kubectl
