---
- name: Download required files
  delegate_to: localhost
  ansible.builtin.import_tasks: download.yaml
  tags:
    - download
    - download_k8s

- name: Configure system and kernel settings
  become: true
  ansible.builtin.import_tasks: system.yaml
  tags:
    - system

- name: Reboot
  become: true
  ansible.builtin.reboot:
  tags:
    - reboot

- name: Configure system settings for Calico networking
  become: true
  ansible.builtin.import_tasks: calico.yaml
  tags:
    - pod_network
    - calico

- name: Enable services used by Longhorn
  when: k8s_common_storage == 'longhorn'
  become: true
  ansible.builtin.import_tasks: longhorn.yaml
  tags:
    - storage
    - longhorn

- name: Enable services used by OpenEBS
  when: k8s_common_storage == 'openebs'
  become: true
  ansible.builtin.import_tasks: openebs.yaml
  tags:
    - storage
    - openebs

- name: Reboot
  become: true
  ansible.builtin.reboot:
  tags:
    - reboot

- name: Install containerd
  become: true
  ansible.builtin.import_tasks: containerd_install.yaml
  tags:
    - container_runtime
    - containerd

- name: Install CNI plugins
  become: true
  ansible.builtin.import_tasks: cni_plugins.yaml
  tags:
    - cni_plugins

- name: Configure containerd
  become: true
  ansible.builtin.import_tasks: containerd_config.yaml
  tags:
    - container_runtime
    - containerd

- name: Install & configure crictl
  become: true
  ansible.builtin.import_tasks: crictl.yaml
  tags:
    - container_tools
    - cri_tools
    - crictl

- name: Install kubelet, kubeadm, and kubectl
  become: true
  ansible.builtin.import_tasks: k8s_tools.yaml
