---
- name: Provision GitLab Runner
  hosts: gitlab_runner
  tasks:
    - name: Check if using cloud-init
      ansible.builtin.raw: cloud-init --version
      register: cloudinit_version_output
      changed_when: false
      ignore_errors: true

    - name: Wait for cloud-init to finish
      when: cloudinit_version_output.rc == 0
      become: true
      ansible.builtin.raw: cloud-init status --wait
      register: cloudinit_status_wait_output
      failed_when: cloudinit_status_wait_output.rc == 1
      changed_when: true

    - name: Check if Python exists
      ansible.builtin.raw: python --version
      register: python_version_output
      changed_when: false
      ignore_errors: true

    - name: Install Python
      when: not ansible_check_mode and python_version_output.rc != 0
      become: true
      ansible.builtin.raw: dnf install -y python
      changed_when: true

    - name: Upgrade all packages
      when: not ansible_check_mode and cloudinit_version_output.rc != 0
      become: true
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Reboot
      become: true
      ansible.builtin.reboot:

    - name: Configure as GitLab Runner
      ansible.builtin.import_role:
        name: gitlab_runner
