---
- name: Provision GitLab Runner
  hosts: gitlab_runner
  tasks:
    - name: Upgrade all packages
      become: true
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Reboot
      become: true
      ansible.builtin.reboot:

    - name: Configure as GitLab Runner
      ansible.builtin.import_role:
        name: gitlab_runner
