---
- name: Setup Kubernetes control plane node
  hosts: pve
  remote_user: root
  tasks:
    - name: Configure Kubernetes nodes
      ansible.builtin.import_role:
        name: k8s
      vars:
        k8s_pve_ignition_path: "{{ ignition_path }}"
        k8s_ign_ssh_authorized_keys: "{{ ign_authorized_ssh_keys }}"
