---
- name: Copy kubeadm join configuration
  ansible.builtin.template:
    src: kubeadm_join.yaml.j2
    dest: /etc/kubeadm_join.yaml
    mode: "644"
  register: kubeadm_join_config_output

- name: Join Kubernetes cluster as a control plane node
  when: k8s_control_plane_secondary_join_command and k8s_control_plane_secondary_certificate_key
  changed_when: true
  ansible.builtin.command:
    argv:
      - kubeadm
      - join
      - --config={{ kubeadm_join_config_output.dest }}

- name: Complete Kubernetes control plane post-initialization
  ansible.builtin.import_role:
    name: k8s_control_plane_post
