---
- name: Setup control plane
  ansible.builtin.import_role:
    name: k8s_control_plane
  vars:
    k8s_control_plane_vmid: 121
    k8s_control_plane_ip: 192.168.1.21
    k8s_control_plane_ign_ssh_authorized_keys: "{{ k8s_ign_ssh_authorized_keys }}"
    k8s_control_plane_pve_ignition_path: "{{ k8s_pve_ignition_path }}"
    k8s_control_plane_k8s_common_version: "{{ k8s_common_version }}"
    k8s_control_plane_k8s_common_base_url: "{{ k8s_common_base_url }}"
    k8s_control_plane_k8s_misc_version: "{{ k8s_misc_version }}"
    k8s_control_plane_k8s_misc_base_url: "{{ k8s_misc_base_url }}"
    k8s_control_plane_k8s_volume_plugin_dir: "{{ k8s_volume_plugin_dir }}"
    k8s_control_plane_k8s_cluster_endpoint: "{{ k8s_cluster_endpoint }}"
    k8s_control_plane_k8s_service_subnet: "{{ k8s_service_subnet }}"
    k8s_control_plane_k8s_pod_subnet: "{{ k8s_pod_subnet }}"
