---
download_dir: "~/Downloads/k8s_ansible"
k8s:
  # This value is for prod infra; test infra sets this variable from the Vagrantfile
  cluster_endpoint: 192.168.1.20
  version: 1.33.1
  runc_version: 1.3.0
  containerd_version: 2.1.1
  cni_plugins_version: 1.7.1
  crictl_version: 1.33.0
  storage: openebs

flux_github_token: "{{ vault_flux_github_token }}"
