---
- name: Modify kube-vip StaticPod manifest
  ansible.builtin.replace:
    path: /etc/kubernetes/manifests/kube-vip.yaml
    regexp: '(\s+)path: /etc/kubernetes/admin.conf'
    replace: '\1path: /etc/kubernetes/super-admin.conf'

- name: Initialize Kubernetes control plane
  changed_when: true
  ansible.builtin.command:
    argv:
      - kubeadm
      - init
      - --control-plane-endpoint={{ k8s_cluster_endpoint }}:6443
      - --upload-certs
      - --pod-network-cidr={{ k8s_control_plane_primary_pod_network_cidr }}

- name: Complete Kubernetes control plane post-initialization
  ansible.builtin.import_role:
    name: k8s_control_plane_post

- name: Apply kube-router CNI/pod networking
  changed_when: true
  ansible.builtin.command:
    argv:
      - kubectl
      - apply
      - --filename={{ k8s_control_plane_primary_kube_router_url }}
