---
- name: Modify kube-vip StaticPod manifest
  become: true
  ansible.builtin.replace:
    path: /etc/kubernetes/manifests/kube-vip.yaml
    regexp: '(\s+)path: /etc/kubernetes/admin.conf'
    replace: '\1path: /etc/kubernetes/super-admin.conf'

- name: Copy kubeadm init configuration
  become: true
  ansible.builtin.template:
    src: kubeadm_init.yaml.j2
    dest: /etc/kubeadm_init.yaml
    mode: "644"
  register: kubeadm_init_config_output

- name: Initialize Kubernetes control plane
  become: true
  ansible.builtin.command:
    argv:
      - kubeadm
      - init
      - --upload-certs
      - --config={{ kubeadm_init_config_output.dest }}
  changed_when: true
  tags:
    - kubeadm_init

- name: Complete Kubernetes control plane post-initialization
  ansible.builtin.import_role:
    name: k8s_control_plane_post

- name: Apply kube-router CNI/pod networking
  block:
    - name: Install Tigera operator
      ansible.builtin.command:
        argv:
          - kubectl
          - create
          - --filename={{ k8s_control_plane_primary_tigera_operator_url }}
      changed_when: true

    - name: Wait for Tigera operator to finish installation
      ansible.builtin.command:
        argv:
          - kubectl
          - --namespace=tigera-operator
          - rollout
          - status
          - deployment
          - tigera-operator
          - --timeout=120s
      changed_when: false

    - name: Wait
      ansible.builtin.wait_for:
        timeout: 15

    - name: Copy Calico installation manifest
      become: true
      ansible.builtin.template:
        src: calico.yaml.j2
        dest: /etc/calico.yaml
        mode: "644"
      register: calico_template_output

    - name: Install Calico
      become: true
      ansible.builtin.command:
        argv:
          - kubectl
          - create
          - --filename={{ calico_template_output.dest }}
      changed_when: true

    - name: Wait for calico-system namespace to be created
      ansible.builtin.command:
        argv:
          - kubectl
          - wait
          - --for=create
          - namespace/calico-system
          - --timeout=120s
      changed_when: false

    - name: Wait
      ansible.builtin.wait_for:
        timeout: 15

    - name: Wait for Calico to finish installation
      ansible.builtin.command:
        argv:
          - kubectl
          - --namespace=calico-system
          - wait
          - --for=jsonpath=.status.numberReady=1
          - daemonset.apps/calico-node
          - --timeout=120s
      changed_when: false
