---
# runc
k8s_common_runc_version: 1.3.0
k8s_common_runc_url: https://github.com/opencontainers/runc/releases/download/v{{ k8s_common_runc_version }}/runc.amd64

# containerd
k8s_common_containerd_version: 2.1.1
k8s_common_containerd_archive: containerd-{{ k8s_common_containerd_version }}-linux-amd64.tar.gz
k8s_common_containerd_url: https://github.com/containerd/containerd/releases/download/v{{ k8s_common_containerd_version }}/{{ k8s_common_containerd_archive }}
k8s_common_containerd_service_url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service

# CNI Plugins
k8s_common_cni_plugins_version: 1.7.1
k8s_common_cni_plugins_archive: cni-plugins-linux-amd64-v{{ k8s_common_cni_plugins_version }}.tgz
k8s_common_cni_plugins_url: https://github.com/containernetworking/plugins/releases/download/v{{ k8s_common_cni_plugins_version }}/{{ k8s_common_cni_plugins_archive }}

# crictl
k8s_common_crictl_version: 1.33.0
k8s_common_crictl_archive: crictl-v{{ k8s_common_crictl_version }}-linux-amd64.tar.gz
k8s_common_crictl_url: https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ k8s_common_crictl_version }}/{{ k8s_common_crictl_archive }}

# kubelet & kubeadm
k8s_common_version: 1.33.1
k8s_common_base_url: https://dl.k8s.io/release/v{{ k8s_common_version }}/bin/linux/amd64

# kubelet service
k8s_common_kubelet_version: 0.16.2
k8s_common_kubelet_base_url: https://raw.githubusercontent.com/kubernetes/release/v{{ k8s_common_kubelet_version }}/cmd/krel/templates/latest
k8s_common_kubelet_service_url: "{{ k8s_common_kubelet_base_url }}/kubelet/kubelet.service"
k8s_common_kubelet_config_url: "{{ k8s_common_kubelet_base_url }}/kubeadm/10-kubeadm.conf"

k8s_common_storage: openebs
