---
flux_git_provider: github

flux_github_username: gillwong
flux_github_repository: gitops
flux_github_branch: main
flux_github_path: clusters/homelab

flux_gitlab_username: gillwong
flux_gitlab_repository: gitops
flux_gitlab_branch: main
flux_gitlab_path: clusters/homelab
