---
- name: Bootstrap Flux with GitHub
  ansible.builtin.command:
    cmd: |
      flux bootstrap github
        --components-extra=image-reflector-controller,image-automation-controller
        --token-auth=false
        --read-write-key=true
        --owner={{ flux_github_username }}
        --repository={{ flux_github_repository }}
        --branch={{ flux_github_branch }}
        --path={{ flux_github_path }}
        --personal
  environment:
    GITHUB_TOKEN: "{{ flux_github_token }}"
  changed_when: true
