---
- name: Bootstrap Flux with GitLab
  ansible.builtin.command:
    cmd: |
      /usr/local/bin/flux --kubeconfig /etc/kubernetes/admin.conf bootstrap gitlab
        --components-extra=image-reflector-controller,image-automation-controller
        --token-auth
        --owner={{ flux_gitlab_username }}
        --repository={{ flux_gitlab_repository }}
        --branch={{ flux_gitlab_branch }}
        --path={{ flux_gitlab_path }}
        --personal
  environment:
    GITLAB_TOKEN: "{{ flux_gitlab_token }}"
  changed_when: true
